with open('/home/ziya/Documents/My_Python_journy/Files&Exceptions/pi_digits.txt') as file_object:
    contents = file_object.read()
    
print(contents)